
CREATE TABLE ASESOR(
ID_ASESOR        VARCHAR2(13) NOT NULL,
USERNAME    VARCHAR2(20) NOT NULL,
NOMBRE_ASESOR            VARCHAR2(50) NOT NULL,
APELLIDO_ASESOR          VARCHAR2(50) NOT NULL,
TELEFONO_ASESOR         VARCHAR2(10) NOT NULL,
CONTRASENA         VARCHAR2(50) NOT NULL,
PRIMARY KEY (ID_ASESOR)
);

DROP TABLE CLIENTE;
CREATE TABLE CLIENTE(
ID_CLIENTE        VARCHAR2(13) NOT NULL,
NOMBRE_CLIENTE            VARCHAR2(50) NOT NULL,
APELLIDO_CLIENTE          VARCHAR2(50) NOT NULL,
TELEFONO_CLIENTE         VARCHAR2(10) NOT NULL,
CATEGORIA         VARCHAR2(2) NOT NULL,
ASESORADO          NUMBER(1),
PRIMARY KEY (ID_CLIENTE)
);

DROP TABLE LLAMADA;
CREATE TABLE LLAMADA(
ID_LLAMADA        VARCHAR2(13) NOT NULL,
ASESOR_LLAMADA    VARCHAR2(13) NOT NULL,
CLIENTE_LLAMADA    VARCHAR2(13) NOT NULL,
TELEFONO_LLAMADA    VARCHAR2(10) NOT NULL,
TIEMPO_LLAMADA   VARCHAR2(10) NOT NULL,
PRIMARY KEY (ID_LLAMADA),
FOREIGN KEY (ASESOR_LLAMADA) REFERENCES ASESOR,
FOREIGN KEY (CLIENTE_LLAMADA) REFERENCES CLIENTE
);

INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, APELLIDO_CLIENTE, TELEFONO_CLIENTE, CATEGORIA, ASESORADO) VALUES ('1234567','CAMILO','GARCIA','3005671090','1',0);
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, APELLIDO_CLIENTE, TELEFONO_CLIENTE, CATEGORIA, ASESORADO) VALUES ('7654321','DAVID','GIRALDO','3002349089','2',0);
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, APELLIDO_CLIENTE, TELEFONO_CLIENTE, CATEGORIA, ASESORADO) VALUES ('1017208','JULIAN','GARCIA','3005671090','3',0);

INSERT INTO ASESOR (ID_ASESOR, USERNAME, NOMBRE_ASESOR, APELLIDO_ASESOR, TELEFONO_ASESOR, CONTRASENA) VALUES ('1111111','ADMIN','ANDRES','GARCIA','3004274116','123');

INSERT INTO LLAMADA (ID_LLAMADA, ASESOR_LLAMADA, CLIENTE_LLAMADA, TELEFONO_LLAMADA, TIEMPO_LLAMADA) VALUES ('7290530' , '1111111' , '7654321' , '3002349089' , '0');