
CREATE TABLE ASESOR(
ID_ASESOR        VARCHAR2(13) NOT NULL,
USERNAME    VARCHAR2(20) NOT NULL,
NOMBRE_ASESOR            VARCHAR2(50) NOT NULL,
APELLIDO_ASESOR          VARCHAR2(50) NOT NULL,
TELEFONO_ASESOR         VARCHAR2(10) NOT NULL,
CONTRASENA         VARCHAR2(50) NOT NULL,
PRIMARY KEY (ID_ASESOR)
);

CREATE TABLE CLIENTE(
ID_CLIENTE        VARCHAR2(13) NOT NULL,
NOMBRE_ASESOR            VARCHAR2(50) NOT NULL,
APELLIDO_ASESOR          VARCHAR2(50) NOT NULL,
TELEFONO_ASESOR         VARCHAR2(10) NOT NULL,
CATEGORIA         VARCHAR2(2) NOT NULL,
PRIMARY KEY (ID_CLIENTE)
);

DROP TABLE LLAMADA;
CREATE TABLE LLAMADA(
ID_LLAMADA        VARCHAR2(13) NOT NULL,
ASESOR_LLAMADA    VARCHAR2(13) NOT NULL,
CLIENTE_LLAMADA    VARCHAR2(13) NOT NULL,
TELEFONO_LLAMADA    VARCHAR2(10) NOT NULL,
TIEMPO_LLAMADA   VARCHAR2(10) NOT NULL,
PRIMARY KEY (ID_LLAMADA),
FOREIGN KEY (ASESOR_LLAMADA) REFERENCES ASESOR,
FOREIGN KEY (CLIENTE_LLAMADA) REFERENCES LLAMADA
);